# Generated by Django 6.1.2 on 2026-10-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationGeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1000, unique=True)),
                ('features', models.JSONField(default=list)),
                ('checked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='coordinate_quality',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('city', 'Approximate city location'), ('address', 'Address-level geocoder match'), ('venue', 'Station-name geocoder match')], db_index=True, default='unverified', max_length=16),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='coordinate_source',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='geocode_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='geocode_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='geocode_error',
            field=models.TextField(blank=True),
        ),
    ]
