# Generated by Django 6.1.2 on 2026-10-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_station_coordinate_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='coordinate_quality',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('city', 'Approximate city location'), ('address', 'Address-level geocoder match'), ('venue', 'Station name/branch match')], db_index=True, default='unverified', max_length=16),
        ),
    ]
